name: papermind
favicon: null
layout_spectrum: 0.9431799000594765
typography_spectrum: 0.8548622203525156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.09049791540019214
  lightness: 0.6638080454431474
  saturation: 0.6992934187874198
  rhythmicContrast: 0.12459945119917393
purpose: []
