name: papermind
favicon: null
layout_spectrum: 0.50002
typography_spectrum: 0.95505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080c0b'
    - '#313332'
    - '#d9d7ca'
    - '#9f9c89'
    - '#7b796c'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
